name = "ThaumtangibleV2"
author = "Egassy & Esét"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c19d672ee5dd691299787932da7d7cb911236437e52403e1bd89fba3774e089"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
