name = "ThaumtangibleV2"
author = "Egassy & Esét"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a333fca488a22bbf5a93a21725fc5a58ec23e6d81bb19af5d450dd9b4137592"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
unsup = "1.2.4"
