name = "ThaumtangibleV2"
author = "Egassy & Esét"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a4fa112927755d00a199019eaf5092627a184d5053c9bbd2eda5b6db9c5a17e"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
unsup = "1.2.4"
