name = "Aeon's Cobblemon Pack"
author = "Aeonsteel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df363cc485a12a40ca60d7f9be32debb8eca63de93b06ca5a2085dfe5d01b53a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"

[options]
datapack-folder = "global_packs/required_data"
