name = "Aeon's Cobblemon Pack"
author = "Aeonsteel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9dfc9ac1f9178843a02fe62b32134384381da05c26c37d6791666f623d60c71"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"

[options]
datapack-folder = "global_packs/required_data"
