name = "Aeon's Cobblemon Pack"
author = "Aeonsteel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de0809783a11a617370805eeb471f34796f0c80f62a666288c11510d50548c5a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.176"

[options]
datapack-folder = "global_packs/required_data"
