game.setLocalization("en_US", "item.bootsMeteor.name", "Boots of the Meteor");
game.setLocalization("en_US", "OakCase.name", "Oak Case");
game.setLocalization("en_US", "tile.ExtraUtils2:DecorativeSolid.blue_quartz.name", "Blue Quartz");
game.setLocalization("en_US", "tile.ExtraUtils2:DecorativeSolid.endstone_brick.name", "Endstone Brick");
game.setLocalization("en_US", "tile.basemetals.liquid_mercury.name", "Flowing Mercury");
game.setLocalization("en_US", "tb.rec.thaumRod.page.0", "For a long time thaumaturges haven't though about using thaumium as their wand rod. But you are not just another thaumaturge. You have applied your knowledge to create a wand rod out of Thaumic Metal, otherwise known as Thaumium. However, thaumium seems to be way too inert. An addition of Salis Mundus solves the problem just fine! The wand is pretty nice, holding up to 450 aspects of each type. You might have seen a lightning or two ocassionaly appearing at the surface of your wand for a mere second, but that is just your imagination, is it?...");
game.setLocalization("en_US", "tc.research_name.TB.PRIMALRODS", "Elemental Wand Cores");
game.setLocalization("en_US", "tc.research_text.TB.PRIMALRODS", "Elemental vis storage");
game.setLocalization("en_US", "tile.blockChute.name", "Chute");
game.setLocalization("options.key", "Key");
game.setLocalization("options.category", "Category");
game.setLocalization("options.search", "Search");
game.setLocalization("options.sort", "Sort");
game.setLocalization("options.showConflicts", "Conflicts");
game.setLocalization("options.showNone", "Show Unbound");