[balancing]
	#How much should a fluid node transfer? (Also applies to chemical nodes if Mekanism is installed)
	# Default: 125
	# Range: 1 ~ 1000000
	fluidNodeTransfer = 125
	#How much should an essence node transfer? (Applies to all essence node types)
	# Default: 50
	# Range: 1 ~ 1000000
	essenceNodeTransfer = 50
	#How much should an item node transfer?
	# Default: 4
	# Range: 1 ~ 64
	itemNodeTransfer = 4
	#How much should an essence battery hold? (Applies to all essence battery types)
	# Default: 10000
	# Range: 1 ~ 1000000
	essenceBatteryMax = 10000
	#How much wires should nodes be able to have? (Applies to all nodes)
	# Default: 4
	# Range: 1 ~ 50
	maxNodeWires = 4
