name = "WR_Testpack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bc6305ef0bcc036a01dbd1ffdb5913c792f0f7696c918c8dac0b7b71c637510"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
unsup = "1.1.6"
