name = "WR_Testpack"
author = "Egassy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dd29ee1fcc05872b345e1ef402ce08eb03b05eb3d4b470b22ed20f94ade646a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
unsup = "1.1.6"
