#Android Parts
recipes.addShaped(<mo:rouge_android_part:0>, [[<mo:tritanium_ingot>, <mo:tritanium_ingot>, <mo:tritanium_ingot>], [<mo:tritanium_ingot>, <mo:isolinear_circuit:3>, <mo:tritanium_ingot>], [null, null, null]]);
recipes.addShaped(<mo:rouge_android_part:3>, [[<mo:tritanium_ingot>, <mo:isolinear_circuit:3>, <mo:tritanium_ingot>], [<mo:tritanium_ingot>, <mo:tritanium_ingot>, <mo:tritanium_ingot>], [<mo:tritanium_ingot>, <mo:tritanium_ingot>, <mo:tritanium_ingot>]]);
recipes.addShaped(<mo:rouge_android_part:2>, [[<mo:tritanium_ingot>, <mo:tritanium_ingot>, <mo:tritanium_ingot>], [<mo:tritanium_ingot>, <mo:isolinear_circuit:3>, <mo:tritanium_ingot>], [<mo:tritanium_ingot>, null, <mo:tritanium_ingot>]]);
recipes.addShaped(<mo:rouge_android_part:0>, [[<mo:tritanium_ingot>, null, <mo:tritanium_ingot>], [<mo:tritanium_ingot>, <mo:isolinear_circuit:3>, <mo:tritanium_ingot>], [<mo:tritanium_ingot>, null, <mo:tritanium_ingot>]]);
recipes.addShaped(<mo:tritainum_spine>, [[<mo:tritanium_ingot>, <mo:tritanium_ingot>, null], [<mo:tritanium_ingot>, <mo:isolinear_circuit:3>, <mo:tritanium_ingot>], [<mo:tritanium_ingot>, <mo:tritanium_ingot>, null]]);
#Pills
recipes.addShaped(<mo:android_pill:0>, [[<minecraft:sugar>, <mo:tritanium_plate>, <minecraft:sugar>], [<minecraft:paper>,<mo:isolinear_circuit:3>, <ore:blockGlassColorless>], [<minecraft:sugar>, <mo:tritanium_plate>, <minecraft:sugar>]]);
recipes.addShaped(<mo:android_pill:2>, [[<minecraft:sugar>, <minecraft:experience_bottle>, <minecraft:sugar>], [<minecraft:paper>,<mo:isolinear_circuit:0>, <ore:stickWood>], [<minecraft:sugar>, <minecraft:experience_bottle>, <minecraft:sugar>]]);
recipes.addShaped(<mo:android_pill:1>, [[<minecraft:sugar>, <minecraft:porkchop>, <minecraft:sugar>], [<minecraft:paper>,<mo:isolinear_circuit:2>, <minecraft:spider_eye>], [<minecraft:sugar>, <minecraft:porkchop>, <minecraft:sugar>]]);