name = "Shrimply Magic"
author = "Egassy"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8b0baff3dbf95b937b4447594219c62df0383bbdcb8e7aa28e1f900637419336"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
unsup = "1.1.15"
