name = "Shrimply Magic"
author = "Egassy"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a907c171e8d4e43c978c052912b09f60a96b38bc48b604bbac5adce90a9e3b9"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
