name = "Shrimply Magic"
author = "Egassy"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ac37bef1394944c1d15b1a71133b7f78d7a6ecedf5c8901227dbd64a42bd7b4"

[versions]
forge = "10.13.4.1614"
minecraft = "1.7.10"
