[flavor_groups.dualhotbar]
name = "Dual Hotbar"
description = "Makes the top row of your inventory (can be changed) into a fully functional extra hotbar, by default on top of your normal hotbar (9 columns, two rows), but can be configured into an 18-slot long hotbar. Client grants partial functionality (hotbar slot swapping), if on server as well then full functionality."
side = "both"
[[flavor_groups.dualhotbar.choices]]
id = "dualhotbar_on"
name = "Yes"
description = "Installs Dual Hotbar."
[[flavor_groups.dualhotbar.choices]]
id = "dualhotbar_off"
name = "No"
description = "Do not install Dual Hotbar."

[flavor_groups.skins]
name = "Skin mods"
description = "Mods that can change the base player skin. Client only."
side = "client"
[[flavor_groups.skins.choices]]
id = "ears"
name = "Ears"
description = "Uses the otherwise-blank space on a modern 64x64 skin in combination with alpha layer encoding to give extra features to your player model, such as ears, wings, a custom cape, breasts, a snout and more. Backports modern skins, but breaks the texture of player head blocks. Client only. No effect (other than seeing other players Ears skins) if you do not have an Ears skin."
[[flavor_groups.skins.choices]]
id = "skinport"
name = "Skinport"
description = "Backports modern skins with no issues."
[[flavor_groups.skins.choices]]
id = "bothskin"
name = "Both"
description = "Installs both Ears and Skinport."
[[flavor_groups.skins.choices]]
id = "noskin"
name = "None"
description = "Do not install a skin mod."

[flavor_groups.tails]
name = "Tails"
description = "Adds extra, pre-set 3-dimensional model parts such as wings, ears and tails to the player model, customized via an in-game editor. Client only."
side = "client"
[[flavor_groups.tails.choices]]
id = "tails_on"
name = "Yes"
description = "Installs Tails."
[[flavor_groups.tails.choices]]
id = "tails_off"
name = "No"
description = "Do not install Tails."

[flavor_groups.cpm]
name = "Customizable Player Models"
description = "Allows creating, editing and displaying an entirely custom player model in-game, with few to no limitations. Client only."
side = "client"
[[flavor_groups.cpm.choices]]
id = "cpm_on"
name = "Yes"
description = "Installs Customizable Player Models."
[[flavor_groups.cpm.choices]]
id = "cpm_off"
name = "No"
description = "Do not install Customizable Player Models."

[flavor_groups.hats]
name = "Hats"
description = "Adds hundreds of hats that can be coloured and tinted. Client only."
side = "both"
[[flavor_groups.hats.choices]]
id = "hats_on"
name = "Yes"
description = "Installs Hats."
[[flavor_groups.hats.choices]]
id = "hats_off"
name = "No"
description = "Do not install Hats."

[flavor_groups.mousetweaks]
name = "Mouse Tweaks"
description = "Tweaks mouse click functionality for better QoL. Allows drag-stacking, shift-click-pickupping, shift-click inventory switching and scroll inventory switching. Client only."
side = "client"
[[flavor_groups.mousetweaks.choices]]
id = "mousetweaks_on"
name = "Yes"
description = "Installs Mouse Tweaks."
[[flavor_groups.mousetweaks.choices]]
id = "mousetweaks_off"
name = "No"
description = "Do not install Mouse Tweaks."

[flavor_groups.inventorytweaks]
name = "Inventory Tweaks"
description = "Allows sorting of inventories and - if enabled - automatic replacment of items and tools with similar items. Client with additional functionality on server, but not required on either."
side = "both"
[[flavor_groups.inventorytweaks.choices]]
id = "inventorytweaks_on"
name = "Yes"
description = "Installs Inventory Tweaks."
[[flavor_groups.inventorytweaks.choices]]
id = "inventorytweaks_off"
name = "No"
description = "Do not install Inventory Tweaks."

[flavor_groups.reauth]
name = "ReAuth"
description = "Allows reauthenticating without restarting the instance, fixing failed authentication bugs. Client only."
side = "client"
[[flavor_groups.reauth.choices]]
id = "reauth_on"
name = "Yes"
description = "Installs ReAuth."
[[flavor_groups.reauth.choices]]
id = "reauth_off"
name = "No"
description = "Do not install ReAuth."

[metafile.dual-hotbar]
flavors = "dualhotbar_on"
[metafile.ears]
flavors = ["ears", "bothskin"]
[metafile.skinport]
flavors = ["skinport", "bothskin"]
[metafile.tails]
flavors = "tails_on"
[metafile.custom-player-models]
flavors = "cpm_on"
[metafile.hats]
flavors = "hats_on"
[metafile.mousetweaks]
flavors = "mousetweaks_on"
[metafile.inventory-tweaks]
flavors = "inventorytweaks_on"
[metafile.reauth]
flavors = "reauth_on"