import mods.thaumcraft.Research;


Research.orphanResearch("TB.Thauminite");
Research.orphanResearch("CAP_thauminite");
Research.orphanResearch("TB.VoidAnvil");
Research.orphanResearch("TB.VoidSeed");
Research.orphanResearch("ROD_tbvoid");
Research.orphanResearch("ROD_tbthaumium");
Research.orphanResearch("TB.Lazullia");
Research.orphanResearch("TB.Ashroom");
Research.orphanResearch("TB.NodeFoci.Stability");
Research.orphanResearch("TB.NodeFoci.Unstable");
Research.orphanResearch("TB.NodeFoci.Hunger");
Research.orphanResearch("TB.NodeFoci.Sinister");
Research.orphanResearch("TB.NodeFoci.Bright");
Research.orphanResearch("TB.NodeFoci.Destr");
Research.orphanResearch("TB.Ukulele");
Research.orphanResearch("TB.Ukulele.Confusion");
Research.orphanResearch("TB.Ukulele.Buffs");
Research.orphanResearch("TB.Ukulele.Growth");
Research.orphanResearch("TB.Ukulele.Knowledge");
Research.orphanResearch("TB.Ukulele.Love");
Research.orphanResearch("TB.Ukulele.Sanity");
Research.orphanResearch("TB.Ukulele.Resistance");
Research.orphanResearch("TB.Ukulele.Electric");
Research.orphanResearch("TB.EnderSapling");
Research.orphanResearch("TB.PeacefulSapling");
Research.orphanResearch("TB.NetherSapling");

Research.removeResearch("TB.Thauminite");
Research.removeResearch("CAP_thauminite");
Research.removeResearch("TB.VoidAnvil");
Research.removeResearch("TB.VoidSeed");
Research.removeResearch("ROD_tbvoid");
Research.removeResearch("ROD_tbthaumium");
Research.removeResearch("TB.Lazullia");
Research.removeResearch("TB.Ashroom");
Research.removeResearch("TB.NodeFoci.Stability");
Research.removeResearch("TB.NodeFoci.Unstable");
Research.removeResearch("TB.NodeFoci.Hunger");
Research.removeResearch("TB.NodeFoci.Sinister");
Research.removeResearch("TB.NodeFoci.Bright");
Research.removeResearch("TB.NodeFoci.Destr");
Research.removeResearch("TB.Ukulele");
Research.removeResearch("TB.Ukulele.Confusion");
Research.removeResearch("TB.Ukulele.Buffs");
Research.removeResearch("TB.Ukulele.Growth");
Research.removeResearch("TB.Ukulele.Knowledge");
Research.removeResearch("TB.Ukulele.Love");
Research.removeResearch("TB.Ukulele.Sanity");
Research.removeResearch("TB.Ukulele.Resistance");
Research.removeResearch("TB.Ukulele.Electric");
Research.removeResearch("TB.EnderSapling");
Research.removeResearch("TB.PeacefulSapling");
Research.removeResearch("TB.NetherSapling");
Research.removeResearch("TB.ARCANEEAR");

game.setLocalization("en_US", "tb.rec.redlon.page.0", "Redstone<BR>Melon<BR>REDSTONE<BR>MELON<BR>REDSTONE<BR>MELON<BR>REDSTONE MELON<BR>REDSTONE MELON<BR>REDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELONREDSTONEMELON");
mods.thaumcraft.Warp.addToResearch("TB.Redlon", 4);
mods.thaumcraft.Warp.addToItem(<thaumicbases:redlonSeeds>, 4);
game.setLocalization("en_US", "tc.research_text.TB.Tobacco.Eldritch", "Henderson's Smoke");
setLocalization("en_US", "tc.research_text.TB.Revolver.Primal", "What lies beyond lightspeed...");
setLocalization("en_US", "tc.research_name.TB.Revolver.Atropods", "Revolver Upgrade: Bane Of Arthopods");

game.setLocalization("en_US", "tb.rec.tobacco.page.0", "Sometimes a thaumaturge just wants some resting from all those horrors of the thaumaturgy. They want their mind clear and concentrated on the tasks. Other thaumaturges are known to smoke some kind of tobacco, but it harms the health of the thaumaturge a great deal, and poisoning is rarely well advised. You do not need this. You have managed to create a plant that functions just like a tobacco, but is absolutely fine for your health! Unfortunately you are sure that your plant is the only one safe, and that no-one besides you can replicate it. Oh well.");
game.setLocalization("en_US", "tb.rec.cryingObs.page.0", "Should a thaumaturge die they will reappear next to the bed they last slept on. However beds are unreliable - they can be blown up, and 'you can only sleep at night'. Also, 'you may not sleep now, there are monsters nearby'. Or even 'this bed is already occupied'. It's time to stop that nonsense! By infusing properties of the bed into Obsidian you have created Crying Obsidian. Putting two atop each other will form an obelisk, which can be used in place of sleep. You will always respawn near the last obelisk you've used. Sleeping in bed resets the spawn location to the bed.");
#game.setLocalization("en_US", "tb.rec.eDec.page.0", "Sometimes a thaumaturge needs more knowledge to continue their research. Sure, he can explore the world, or use the Deconstruction Table, but what else? You have managed to create a device that will slowly kill creatures upon it and send knowledge of those creatures directly into it's owner's brain. To become an 'owner' of this thing just click it once it is placed in the world. However, the knowledge gets corrupted with the distance, and may harm the mind of the owner if it is travelling significant distances.");
game.setLocalization("en_US", "tb.rec.foci.speed.page.0", "Speed Focus increases the speed at which node operates 5 times. It may be hard for a thaumaturge to see this in action, but should they use their wand, or any of their vis using devices, it will become quite clear.");
game.setLocalization("en_US", "tb.rec.enchantments.page.1", "Weapons, enchanted with Elder Wisdom will have a chance to provide the thaumaturge using them with some knowledge of object they slays.");
game.setLocalization("en_US", "tb.rec.enchantments.page.3", "Weapons, enchanted with Magic Touched will provide thaumaturge using them with more primal aspects from enemies they kills.");
game.setLocalization("en_US", "tb.rec.enchantments.page.4", "Weapons, enchanted with Vaporising enchantment will have a chance to provide the thaumaturge using them with some crystallized life essentia of creatures they slays.");
game.setLocalization("en_US", "tb.rec.campfire.page.0", "If a person wanders around for example in the forest when it is getting dark and is too far away from home to go to his bed, they are probably stuck there in the darkness with monsters all around. However, you are a thaumaturge, surely you can solve that minor problem! You have discovered a way to make a magical campfire! To light it up you first need to put a log into it - magical logs may be more long-lasting. Next just insert any fuel in it. Your campfire is made with magic, so monsters around it will get scared and run away, just as creepers run away from cats! However, sometimes a hunger will make the monster ignore the campfire to a certain extend - it is not 100% safe.");
game.setLocalization("en_US", "tb.rec.plax.page.0", "Sometimes a thaumaturge just needs to get 'em some string - for magical candles or for magical clothes - it does not matter that much what for. And sometimes a thaumaturge just does not want to fight spiders for endless nights or shear sheep for wool to process later. You have applied the knowledge of plants and nature you've just learned to solve the problem for you. The result is a strange crop, named Plax, which will grow on farmland in 8 stages and once fully grown will produce 3 string! It functions just like a regular wheat crop - it also needs light and will only grow on farmland.");
game.setLocalization("en_US", "tb.rec.revolver.duel.page.0", "Sometimes the simple words are not enough, and a Thaumaurge needs to physically prove themselves. Prior to the revolver discovery that could only be done via mundane swords and bows. Now a Thaumaturge and his offender can resolve their issue like the gentry do - with their guns! This upgrade will make the revolver much more potent against other players, and will not affect the effectiveness against others.<BR>Max Level: §6§l 5 §r§0<BR>Conflicts with: §nPower§r, §0§nSilver§r, §0§nBane Of Atropods§r, §0§nBane Of Eldritch§r, §0§nEldritch§r");
game.setLocalization("en_US", "tb.rec.metalleat.page.0", "Sometimes a thaumaturge needs some metallum for his ore processing. And there goes an iron ingot. Sometimes a thaumaturge needs metallum for his crafts. And there goes more iron. You have discovered a way to put an end to this misery - by infusing a regular wheat seeds in a crucible with some metallum and victus to keep the life in the seeds you have managed to create a plant, that grows exactly like wheat, but gets tough and metallic in the latest stages of growth. It then can be harvested to obtain some Iron Nuggets. This discovery asks more questions than it answeres though, and you might need to research it further... As far as you can tell you can't replicate the same with thaumium.");
game.setLocalization("en_US", "tb.rec.tobacco.page.1", "To properly rest a thaumaturge like you needs 3 things - a nice house, and you should have one already, his smoking pipe and some tobacco. To properly make the tobacco a thaumaturge must grind the leaves of a plant. You might need a Pestle and Mortar to do so. You will also need your smoking pipe, but you do not want those mundane pipes, do you? You have discovered a way to properly infuse some Greatwood planks to make a perfect pipe. It is also good for your magic contact, since it has a Salis Mundus as one of it's components.");
game.setLocalization("en_US", "tb.rec.etobacco.page.0", "You have discovered a way to infuse regular tobacco powder with some eldritch energy. The result may not be that safe to smoke, however, should a thaumaturge smoke such a thing his vision will go grim for some time. Thaumaturge with such a vision should not look at living beings. It is also possible to attract the attention of "eldritch" by doing so, however the chances are low. The tobacco might cause sanity problems!");
game.setLocalization("en_US", "tb.rec.witobacco.page", "You have gone beyond the relaxing properties of the tobacco. Infusing your tobacco with knowledge sure was a great idea - you have managed to create a tobacco, which puts you in a crystal clear mind state once you smoke it. The effect lasts a mere second, though it is more than enough to make a shocking discovery or two. However, you are afraid, that you may also see something horrible there, which will corrupt your mind... Well, who does not risk - does not get his reward, right?");
game.setLocalization("en_US", "tb.rec.ttobacco.page.0", "You are not quite sure why you have even discovered this. Sure, now you can infuse your tobacco with taint, forever changing it, so anyone, who smokes it will have his mind corrupted by taint, and all the horrors of the dark will appear in his mind, but what is it even usefull for? The taint pieces also leave tiny signs on the pipe of the smoker. You are interested in the ways this will affect things like silverwood... Probably nothing good though.");
game.setLocalization("en_US", "tb.rec.spikeIron.page.0", "Sometimes a thaumaturge just wants to stydy his researches. Calm, alone and without any zombies at his back. Sure, sometimes a door might just be enough. Sometimes, however, a thaumaturge may want those fools to suffer. It's a shame thaumaturgy does not offer a way of passivly killing enemies... Or does it? You have managed to create a block, that will damage everyone who steps on it. However it also tears apart items dropped by fools. There might be a way to resolve this problem... A thaumaturge may also notice, that after killing a creature the spikes get covered in blood. To wipe the blood out you need to use your Enchanted Fabric on the spikes. The fabric will get covered in blood, but it can be cleared in a crucible.");
game.setLocalization("en_US", "tb.rec.drainFoci.page.0", "Sometimes a Thaumaturge wants to live under the sea, §m next to his pineapple §r in his beautifull water dome. However, building underwater is a huge pain... Untill now. This wand foci will resolve the problem! It will destroy blocks of water the thaumaturge is looking at, without making all nearby water blocks flow! In other ways, it is perfect in creatin tunnels! However, magic can only harness the water so long, and the water will eventually return to it's normal flowing state. It will also do so should a block be placed next to the not-flowing water block.");
game.setLocalization("en_US", "tb.rec.expFoci.page.0", "The only ways of enchanting for a regular thaumaturge is either by using his own life essence to roll the dices or by using the infusion matrix to controll the process. Either way some life essence is required. The most efficent way of collecting it is by... killing mobs? Mining? You think, that thaumaturgy must offer something else, more 'magical'. And this is it. This foci will instantly break the block it is used on, providing a thaumaturge with twice the experience the block would usually drop! Blocks, which usually do not provide experience will drop some based on the Potency level of the foci.");
game.setLocalization("en_US", "tb.rec.revolver.page.0", "Henderson's Smoke");
game.setLocalization("en_US", "tc.research_text.TB.Tobacco.Eldritch", "Henderson's Smoke");
game.setLocalization("en_US", "tc.research_text.TB.Tobacco.Eldritch", "Henderson's Smoke");
game.setLocalization("en_US", "tc.research_text.TB.Tobacco.Eldritch", "Henderson's Smoke");
game.setLocalization("en_US", "tc.research_text.TB.Tobacco.Eldritch", "Henderson's Smoke");